[env:esp32-s3-zero]
platform = espressif32
framework = arduino
board = esp32-s3-devkitm-1

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L

; --- ĐỔI TÊN FILE PHÂN VÙNG THÀNH DEFAULT.CSV ---
board_build.partitions = default.csv

board_build.flash_mode = qio
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
lib_deps =
    spaziochirale/Chirale_TensorFLowLite
    madhephaestus/ESP32Encoder@^0.11.7
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
